In [ ]:
import numpy as np


In [ ]:
steps=100
input_features=10
hidden_state=5

In [ ]:
inputs=np.random.normal(0,1,(steps,input_features))
state_T=np.zeros((hidden_state))

In [ ]:
w=np.random.normal(0,1,(hidden_state,hidden_state))
u=np.random.normal(0,1,(hidden_state,input_features))
b=np.random.normal(0,1,(hidden_state))


In [ ]:
res=[]
for i in range(steps):
  output=np.tanh(w@state_T+u@inputs[i]+b)
  res.append(output)
  state_T=output
res

[array([-0.91554507,  0.40308986, -0.81817018, -0.10177964, -0.99822656]),
 array([-0.9992927 , -0.99982988, -0.99853028, -0.8219264 , -0.99991654]),
 array([0.93577586, 0.99999914, 0.99750546, 0.99975802, 0.99862713]),
 array([ 0.64225203,  0.86233915, -0.99999248, -0.98470575,  0.53460918]),
 array([0.99983484, 1.        , 0.99991131, 0.99994595, 0.87023889]),
 array([ 0.9335496 , -0.99998653, -0.02230326, -0.99936997, -0.99950669]),
 array([0.99703331, 0.99999984, 0.99996518, 0.40840661, 0.95283105]),
 array([-0.99823577, -0.99999708, -0.8758099 ,  0.98232614, -0.99989078]),
 array([ 0.99817834,  0.99999697,  0.9826074 , -0.99505682,  0.87191744]),
 array([-0.99997246, -0.99999997, -0.99157664,  0.97451092, -0.99999802]),
 array([ 0.56766596,  0.99999999, -0.9218234 ,  0.99846155,  0.99584927]),
 array([-0.93344056, -0.99999977, -0.4600595 , -0.90944893, -0.99999925]),
 array([0.97540655, 0.99997317, 0.99999999, 0.99999755, 0.97697103]),
 array([-0.24642793,  0.83562605, -0.99972312

In [ ]:
w.shape,state_T.shape

((2,), (5,))